spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##JAVA_2024
    password: java
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      second-level-cache: false
      ddl-auto: none
    show-sql: true
    format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
